import type { FurnitureDef, FurnitureSlot } from '../game/types';

export const FURNITURE_SLOTS: Array<{ slot: FurnitureSlot; label: string }> = [
  { slot: 'hearth', label: 'Hearth' },
  { slot: 'lights', label: 'Lighting' },
  { slot: 'window', label: 'Window' },
  { slot: 'wallLeft', label: 'Left Wall' },
  { slot: 'wallRight', label: 'Right Wall' },
  { slot: 'floorRight', label: 'Seating' },
  { slot: 'hearthside', label: 'Fireside' },
  { slot: 'counter', label: 'Bar Counter' },
];

export const FURNITURE: FurnitureDef[] = [
  // ── Hearth ─────────────────────────────────────────────────────────────
  {
    id: 'hearth-sooty',
    slot: 'hearth',
    name: 'Sooty Hearth',
    blurb: 'A fireplace in the sense that there is a place, and occasionally a fire.',
    price: 0,
    unlockLevel: 1,
    bonus: {},
    default: true,
  },
  {
    id: 'hearth-stone',
    slot: 'hearth',
    name: 'Stone Fireplace',
    blurb: 'Warm feet make patient guests. Cold feet make poets.',
    price: 150,
    unlockLevel: 2,
    bonus: { patiencePct: 10 },
  },
  {
    id: 'hearth-grand',
    slot: 'hearth',
    name: 'Grand Hearth',
    blurb: 'Big enough to roast an ox. Please don’t roast the ox in the corner. He’s a regular.',
    price: 900,
    unlockLevel: 7,
    bonus: { patiencePct: 20, tipPct: 5 },
  },
  {
    id: 'hearth-dragon',
    slot: 'hearth',
    name: 'Dragon-Kindled Hearth',
    blurb: 'Lit by Ember personally. Never goes out. Occasionally hiccups.',
    price: 0,
    unlockLevel: 1,
    bonus: { patiencePct: 25, tipPct: 10 },
    special: true,
  },

  // ── Lighting ───────────────────────────────────────────────────────────
  {
    id: 'lights-candles',
    slot: 'lights',
    name: 'Candle Stubs',
    blurb: 'Atmospheric. Mostly because nobody can see anything.',
    price: 0,
    unlockLevel: 1,
    bonus: {},
    default: true,
  },
  {
    id: 'lights-lanterns',
    slot: 'lights',
    name: 'Brass Lanterns',
    blurb: 'Now guests can see the menu. And each other. Mixed reviews.',
    price: 100,
    unlockLevel: 1,
    bonus: { tipPct: 5 },
  },
  {
    id: 'lights-chandelier',
    slot: 'lights',
    name: 'Antler Chandelier',
    blurb: 'The deer donated the antlers willingly. He says they were “last season”.',
    price: 480,
    unlockLevel: 4,
    bonus: { tipPct: 8, patiencePct: 5 },
  },
  {
    id: 'lights-fireflies',
    slot: 'lights',
    name: 'Firefly Jars',
    blurb: 'Unionised fireflies. They take Tuesdays off and they’ve earned it.',
    price: 1100,
    unlockLevel: 8,
    bonus: { tipPct: 10, xpPct: 10 },
  },
  {
    id: 'lights-stars',
    slot: 'lights',
    name: 'Prophetic Star Lanterns',
    blurb: 'A gift from Madame Zephyrine. They twinkle a little brighter before good news.',
    price: 0,
    unlockLevel: 1,
    bonus: { tipPct: 12, xpPct: 10 },
    special: true,
  },

  // ── Window ─────────────────────────────────────────────────────────────
  {
    id: 'window-dusty',
    slot: 'window',
    name: 'Dusty Window',
    blurb: 'You can see the moon through it. Some of the moon.',
    price: 0,
    unlockLevel: 1,
    bonus: {},
    default: true,
  },
  {
    id: 'window-flowers',
    slot: 'window',
    name: 'Window Flower Box',
    blurb: 'Petunias. They have seen things. They will not talk about the things.',
    price: 120,
    unlockLevel: 2,
    bonus: { patiencePct: 5, tipPct: 3 },
  },
  {
    id: 'window-stained',
    slot: 'window',
    name: 'Stained-Glass Window',
    blurb: 'Depicts the Great Ale Flood of ’42. Very tasteful. Very sticky.',
    price: 700,
    unlockLevel: 6,
    bonus: { tipPct: 8, xpPct: 5 },
  },

  // ── Left wall ──────────────────────────────────────────────────────────
  {
    id: 'wall-shield',
    slot: 'wallLeft',
    name: 'Rusty Shield',
    blurb: 'Guaranteed to have blocked at least one sword. Possibly a butter knife.',
    price: 60,
    unlockLevel: 1,
    bonus: { tipPct: 3 },
  },
  {
    id: 'notice-board',
    slot: 'wallLeft',
    name: 'Quest Notice Board',
    blurb: '“Lost: cat. Found: dragon. Please advise.” Adventurers can’t resist a notice board.',
    price: 200,
    unlockLevel: 3,
    bonus: { xpPct: 10 },
    attracts: 'reginald',
  },
  {
    id: 'mounted-antlers',
    slot: 'wallLeft',
    name: 'Jackalope Antlers',
    blurb: 'The jackalope is fine. It just wanted a new look.',
    price: 450,
    unlockLevel: 5,
    bonus: { tipPct: 8 },
  },
  {
    id: 'legendary-tankard',
    slot: 'wallLeft',
    name: 'The Unbreakable Tankard',
    blurb: 'Forged by Grizelda Stonebeard. Troll-proof. Dishwasher safe. Does not talk.',
    price: 0,
    unlockLevel: 1,
    bonus: { tipPct: 10, bonusWordCoins: 1 },
    special: true,
  },
  {
    id: 'ships-wheel',
    slot: 'wallLeft',
    name: 'Captain’s Ship Wheel',
    blurb: 'From Captain Brinebottom’s old ship. Turning it does nothing. Everyone turns it anyway.',
    price: 0,
    unlockLevel: 1,
    bonus: { tipPct: 10, patiencePct: 10 },
    special: true,
  },

  // ── Right wall ─────────────────────────────────────────────────────────
  {
    id: 'painting-goose',
    slot: 'wallRight',
    name: 'Portrait of a Brave Goose',
    blurb: 'Nobody knows who the goose is. Everybody respects the goose.',
    price: 90,
    unlockLevel: 1,
    bonus: { xpPct: 5 },
  },
  {
    id: 'tapestry',
    slot: 'wallRight',
    name: 'Tapestry of the Word Wars',
    blurb: 'Commemorates the great battle of Vowels versus Consonants. Y fought for both sides.',
    price: 600,
    unlockLevel: 6,
    bonus: { xpPct: 10, bonusWordCoins: 1 },
  },
  {
    id: 'ship-bottle',
    slot: 'wallRight',
    name: 'Ship in a Bottle',
    blurb: 'How did they get it in there? Magic. Or a very small, very patient sailor.',
    price: 350,
    unlockLevel: 6,
    bonus: { tipPct: 5 },
    attracts: 'brinebottom',
  },
  {
    id: 'holy-grill',
    slot: 'wallRight',
    name: 'The Holy Grill',
    blurb: 'Found at the end of a very confusing quest. Radiant, ancient, slightly greasy.',
    price: 0,
    unlockLevel: 1,
    bonus: { pricePct: 10 },
    special: true,
  },
  {
    id: 'golden-lute',
    slot: 'wallRight',
    name: 'Barnaby’s Golden Lute',
    blurb: 'Signed by a dragon. The scorch marks are the signature.',
    price: 0,
    unlockLevel: 1,
    bonus: { tipPct: 10, xpPct: 5 },
    special: true,
  },

  // ── Seating ────────────────────────────────────────────────────────────
  {
    id: 'table-wobbly',
    slot: 'floorRight',
    name: 'Wobbly Table',
    blurb: 'One leg is shorter than the others. Nobody agrees which.',
    price: 0,
    unlockLevel: 1,
    bonus: {},
    default: true,
  },
  {
    id: 'table-oak',
    slot: 'floorRight',
    name: 'Sturdy Oak Table',
    blurb: 'Now with four legs of equal length! Guests are suspicious but grateful.',
    price: 180,
    unlockLevel: 2,
    bonus: { patiencePct: 10 },
  },
  {
    id: 'armchair',
    slot: 'floorRight',
    name: 'Squashy Armchair',
    blurb: 'Sit down and you may never get up. Several guests have become furniture.',
    price: 320,
    unlockLevel: 3,
    bonus: { patiencePct: 15 },
  },
  {
    id: 'bard-stage',
    slot: 'floorRight',
    name: 'Bard’s Stage',
    blurb: 'Tip bucket included. Hecklers not included; they bring themselves.',
    price: 420,
    unlockLevel: 4,
    bonus: { tipPct: 12 },
  },
  {
    id: 'reading-nook',
    slot: 'floorRight',
    name: 'Mortimer’s Reading Nook',
    blurb: 'Built by Mortimer for his book club. “No bones in it. Promise.”',
    price: 0,
    unlockLevel: 1,
    bonus: { xpPct: 10, patiencePct: 15 },
    special: true,
  },

  // ── Fireside ───────────────────────────────────────────────────────────
  {
    id: 'cat-basket',
    slot: 'hearthside',
    name: 'Cat Basket',
    blurb: 'Comes with a cat. The cat did not agree to this. The cat is staying anyway.',
    price: 140,
    unlockLevel: 2,
    bonus: { tipPct: 4, patiencePct: 4 },
  },
  {
    id: 'potted-fern',
    slot: 'hearthside',
    name: 'Potted Fern',
    blurb: 'Leafy, lovely, and suspiciously good at listening. Ents love a fern.',
    price: 220,
    unlockLevel: 4,
    bonus: { patiencePct: 8 },
    attracts: 'oakley',
  },
  {
    id: 'hatchling-nest',
    slot: 'hearthside',
    name: 'Hatchling’s Nest',
    blurb: 'Pip swore it was a potato. It was not a potato. She likes warm places and shiny things.',
    price: 0,
    unlockLevel: 1,
    bonus: { xpPct: 15 },
    special: true,
  },
  {
    id: 'oakley-sapling',
    slot: 'hearthside',
    name: 'Oakley’s Sapling',
    blurb: 'Oakley’s long-lost acorn, all grown up. Her first word was “photosynthesis”.',
    price: 0,
    unlockLevel: 1,
    bonus: { patiencePct: 15, xpPct: 5 },
    special: true,
  },

  // ── Bar counter ────────────────────────────────────────────────────────
  {
    id: 'tip-jar',
    slot: 'counter',
    name: 'Tip Jar',
    blurb: 'Labelled “For the Wordsmith’s Retirement”. Currently contains a button.',
    price: 50,
    unlockLevel: 1,
    bonus: { tipPct: 5 },
  },
  {
    id: 'crystal-ball',
    slot: 'counter',
    name: 'Crystal Ball',
    blurb: 'Shows the future. The future is mostly dishes. Fortune tellers find it irresistible.',
    price: 380,
    unlockLevel: 5,
    bonus: { xpPct: 8 },
    attracts: 'zephyrine',
  },
  {
    id: 'brass-register',
    slot: 'counter',
    name: 'Brass Coin Register',
    blurb: 'Ka-ching! Makes every sale feel official. Attracts the attention of the tax office.',
    price: 650,
    unlockLevel: 7,
    bonus: { pricePct: 8 },
    attracts: 'ledgerly',
  },
  {
    id: 'enchanted-quill',
    slot: 'counter',
    name: 'Enchanted Quill',
    blurb: 'Writes down orders by itself and corrects your spelling. Smugly.',
    price: 1000,
    unlockLevel: 8,
    bonus: { hintDiscount: 5, bonusWordCoins: 1 },
  },
  {
    id: 'fizzlewick-grimoire',
    slot: 'counter',
    name: 'Fizzlewick’s Spellbook',
    blurb: 'All the misspelled spells are crossed out, so it’s a very thin book.',
    price: 0,
    unlockLevel: 1,
    bonus: { hintDiscount: 5, xpPct: 10 },
    special: true,
  },
  {
    id: 'royal-seal',
    slot: 'counter',
    name: 'Royal Seal of Excellence',
    blurb: 'Awarded by royal decree, on the recommendation of an anonymous (handsome) inspector.',
    price: 0,
    unlockLevel: 1,
    bonus: { pricePct: 10, tipPct: 5 },
    special: true,
  },
];
