import type { DialogueLine, GuestDef, Mood } from '../game/types';

// Dialogue shorthands keep the scripts below readable.
const g = (text: string, mood?: Mood): DialogueLine => ({ speaker: 'guest', text, mood });
const b = (text: string, mood?: Mood): DialogueLine => ({ speaker: 'barley', text, mood });

export const GUESTS: GuestDef[] = [
  // ════════════════════════════════════════════════════════════════════════
  {
    id: 'barnaby',
    name: 'Barnaby Bramblefoot',
    title: 'Halfling Bard',
    portrait: {
      species: 'halfling',
      skin: '#f2c29b',
      hair: '#a0522d',
      hairStyle: 'curly',
      hat: 'bard',
      hatColor: '#3f7d3a',
      hatAccent: '#d6453d',
      outfit: '#4a8a3f',
      outfitAccent: '#e3b448',
      eyes: 'wide',
      nose: 'button',
      accessories: ['blush', 'freckles'],
    },
    favorites: ['honey-mead', 'frothy-ale'],
    patienceMult: 1,
    tipMult: 1,
    unlock: { level: 1 },
    rumor: 'A bard with more enthusiasm than rhymes is looking for an audience.',
    bio: 'A bard of tremendous enthusiasm and limited rhymes, composing an epic about a dragon he has never met.',
    lines: {
      greet: [
        'Barnaby Bramblefoot, bard extraordinaire! Hold your applause.',
        'Evening! I wrote a new song. It’s about you. Well, mostly about me.',
        'My favourite tavern! Don’t tell the other taverns.',
        'A bard walks into a tavern. That’s the whole joke. I’m the bard.',
      ],
      order: [
        'One {recipe}, if you please! Artists need fuel.',
        'I’ll have the {recipe}. Put it on my tab. My imaginary tab.',
        'A {recipe}, please! It rhymes with... nothing. Blast.',
      ],
      happy: [
        'Magnificent! I shall write a sonnet about this. Or a limerick. Something short.',
        'Bravo! Encore! ...Can food do an encore?',
        'Delicious! It tastes like a standing ovation.',
      ],
      grumpy: [
        'My muse grows impatient. So does my stomach.',
        'I’ve composed three verses about waiting. They’re all in a minor key.',
        'Even my lute is getting peckish.',
      ],
      waiting: ['Hmm hmm hmm... what rhymes with “hungry”?', '*strums impatiently*', 'No rush! Only... a slight rush.'],
      banter: [
        'The Ember ballad is now a trilogy. She wants a fourth. Dragons always want a fourth.',
        'Did you know “orange” rhymes with nothing? I’ve checked. Twice.',
        'I’m writing a song about a tankard. Barley keeps demanding a key change.',
        'I’ve been banned from three taverns for encores. Not this one. Yet.',
      ],
    },
    story: [
      {
        title: 'A Bard Arrives',
        arrive: [
          g('Greetings, new barkeep! Barnaby Bramblefoot: bard, poet, and occasional juggler.', 'happy'),
          g('I am composing the greatest ballad Quillhaven has ever heard: “The Dragon of Mount Grumble”!'),
          b('Have you ever actually met a dragon?'),
          g('Details! Art is about the heart, not the facts.'),
        ],
        order: 'Fuel my genius with a {recipe}, please!',
        done: [
          g('Inspiring! First verse: “Oh dragon, oh dragon, so scaly and... scaly.”', 'happy'),
          g('It needs work. I shall return!'),
        ],
        reward: { coins: 30 },
      },
      {
        title: 'Rhyme Crime',
        arrive: [
          g('Disaster! My ballad is stuck. What rhymes with “dragon”?', 'sad'),
          b('Wagon.'),
          g('A dragon... in a wagon? ...Actually, that’s rather good.', 'surprised'),
          g('Everybody loves a dragon on wheels.', 'happy'),
        ],
        order: 'A {recipe}, please. Rhyming is thirsty work.',
        done: [
          g('Verse two is done! “The dragon rode a wagon, his tail a-dragon-draggin’.”', 'happy'),
          b('I’ve heard worse. Not recently. But I have.'),
        ],
        reward: { coins: 40 },
      },
      {
        title: 'The Turnip Incident',
        arrive: [
          g('Last night I performed at the Rusty Flagon. Someone threw a turnip.', 'sad'),
          g('I caught it and made soup. But my spirit was bruised.'),
          b('The soup too, presumably.'),
        ],
        order: 'I need comfort food. A {recipe}, and make it heroic.',
        done: [
          g('You know what? A turnip is just applause that grew underground.', 'happy'),
          g('I shall perform again! Somewhere with a proper stage. Hint, hint.'),
        ],
        reward: { coins: 50 },
      },
      {
        title: 'Research Trip',
        arrive: [
          g('Big news! I’m going to Mount Grumble to meet a real dragon. For research!', 'happy'),
          b('Brave. Or delicious. We’ll find out.'),
          g('I’ve packed a lute, a notebook, and fire-resistant trousers.'),
        ],
        order: 'A hearty {recipe} for the road, please!',
        done: [
          g('Wish me luck! If I don’t return, sing my ballad at my funeral. The good verses only.'),
          b('That’s a very short funeral.'),
        ],
        reward: { coins: 60 },
      },
      {
        title: 'The Dragon Came Too',
        arrive: [
          g('I’M BACK! And the dragon LOVED the ballad!', 'happy'),
          g('She said it was the worst thing she’d ever heard, and she wants to hear it again.'),
          b('...She?'),
          g('Ember! She’s lovely. She’s parking outside. Well, landing. On the roof.', 'happy'),
          b('ON THE ROOF?', 'surprised'),
        ],
        order: 'Quick, a {recipe} to celebrate!',
        done: [
          g('The Ballad of Ember is complete! Ten verses, four key changes, one wagon.', 'happy'),
          g('Take my old lute. Ember signed it. The scorch marks are her autograph.'),
          g('She says she’ll drop by once your tavern is famous enough. Save her a large table. Or a small field.'),
        ],
        reward: { coins: 120, furniture: 'golden-lute' },
      },
    ],
  },

  // ════════════════════════════════════════════════════════════════════════
  {
    id: 'grizelda',
    name: 'Grizelda Stonebeard',
    title: 'Dwarven Smith',
    portrait: {
      species: 'dwarf',
      skin: '#e3a57b',
      hair: '#c4502a',
      hairStyle: 'braids',
      beard: 'braided',
      hat: 'cap',
      hatColor: '#5b3a24',
      hatAccent: '#8a5a36',
      outfit: '#6b4b3a',
      outfitAccent: '#a7b0b5',
      nose: 'big',
      eyes: 'dot',
      accessories: ['scar', 'earring'],
    },
    favorites: ['dwarven-stout', 'roast-boar', 'hearty-stew'],
    patienceMult: 0.9,
    tipMult: 1.1,
    unlock: { level: 1 },
    rumor: 'A dwarf with a hammer has opinions about the size of your mugs.',
    bio: 'A master smith who believes everything is too small, too flimsy, or both. On a quest to forge the perfect tankard.',
    lines: {
      greet: [
        'Grizelda Stonebeard. I forge things. Mostly things that don’t break.',
        'Evening. Your door handle came off. I fixed it. Now it’s a door handle AND a weapon.',
        'Stonebeard’s here. Brace the furniture.',
      ],
      order: [
        '{recipe}. A proper portion, not a doll’s portion.',
        'One {recipe}. Dwarf-sized. That’s bigger than you think.',
        'A {recipe}, and don’t skimp. I’ll know.',
      ],
      happy: [
        'Now THAT’S a portion. Nearly adequate!',
        'Solid work. Like a good anvil.',
        'I’d forge you a medal, but you’d drop it on your foot.',
      ],
      grumpy: [
        'I’ve forged swords faster than this.',
        'Hmph. My beard grew an inch while I waited.',
        'I’m not angry. This is just my face. Mostly.',
      ],
      waiting: ['*taps a hammer on the counter, rhythmically*', 'Is that a mug or a thimble?', 'I could build a kitchen faster.'],
      banter: [
        'The Unbreakable Tankard is holding up. I tested it on three trolls.',
        'Barley and I have an understanding. He doesn’t comment on my beard.',
        'I’m forging a new anvil. For the old anvil. It gets lonely.',
      ],
    },
    story: [
      {
        title: 'Too Small',
        arrive: [
          g('So you’re the new Wordsmith. Your mugs are pathetic.', 'grumpy'),
          b('EXCUSE me?', 'grumpy'),
          g('Not you, talking mug. You’re... adequate.'),
          b('...I’ll take it.'),
          g('I’m going to forge this tavern a proper tankard. One that survives a dwarf wedding.'),
        ],
        order: 'While I plan: a {recipe}. A big one.',
        done: [g('Good. Now I need inspiration. And iron. Mostly iron.')],
        reward: { coins: 30 },
      },
      {
        title: 'Too Heavy',
        arrive: [
          g('Tankard number one is ready! Solid iron. Forty pounds.', 'happy'),
          g('...It fell through my workbench. And the floor. It lives in my basement now.', 'sad'),
          b('So it’s less of a tankard, more of an anchor.'),
        ],
        order: 'A {recipe}. I need to think lighter thoughts.',
        done: [g('Lighter metal. Mithril, perhaps. Perhaps... slightly smaller. No. Never smaller.')],
        reward: { coins: 40 },
      },
      {
        title: 'Too Magical',
        arrive: [
          g('Tankard number two! Enchanted to never spill.', 'happy'),
          g('Unfortunately it also never pours. It just holds your ale. Forever. Smugly.', 'grumpy'),
          b('I like it already.'),
        ],
        order: 'A {recipe}. In a normal bowl. For now.',
        done: [g('Enchantments are tricky. Wizards make it look easy. Most wizards. Not Fizzlewick.')],
        reward: { coins: 50 },
      },
      {
        title: 'Too Chatty',
        arrive: [
          g('Tankard number three can talk.', 'sad'),
          b('Oh no. Competition.', 'surprised'),
          g('It only knows one word. “Refill.” It says it every four seconds.'),
          g('I buried it in the garden. I can still hear it.'),
        ],
        order: 'A {recipe}. And some quiet.',
        done: [g('One more try. I’ll need fire. Real fire. Dragon fire, if you know anyone.')],
        reward: { coins: 60 },
      },
      {
        title: 'Just Right',
        arrive: [
          g('It’s done. The Unbreakable Tankard.', 'happy'),
          g('Mithril rim. Troll-proof handle. Tempered in a volcano. Doesn’t talk.'),
          b('...Is it better than me?'),
          g('Different league, mug. You’re sentimental. This is structural.'),
          g('It’s yours, Wordsmith. Hang it where everyone can see.'),
        ],
        order: 'Let’s toast it properly. A {recipe}!',
        done: [g('Perfect. I’ll be back to check nobody’s dented it. Nobody can. But I’ll check.', 'happy')],
        reward: { coins: 100, furniture: 'legendary-tankard' },
      },
    ],
  },

  // ════════════════════════════════════════════════════════════════════════
  {
    id: 'fizzlewick',
    name: 'Fizzlewick the Befuddled',
    title: 'Wizard (Almost)',
    portrait: {
      species: 'human',
      skin: '#f1c7a8',
      hair: '#ececec',
      hairStyle: 'long',
      beard: 'long',
      hat: 'wizard',
      hatColor: '#5b3b8c',
      hatAccent: '#f4d35e',
      outfit: '#4b3a8c',
      outfitAccent: '#f4d35e',
      nose: 'long',
      eyes: 'dot',
      accessories: ['glasses', 'wrinkles'],
    },
    favorites: ['wizards-fizz', 'barkroot-tea'],
    patienceMult: 1.1,
    tipMult: 1,
    unlock: { level: 2 },
    rumor: 'Something keeps turning the town fountain into lemonade. Someone’s spelling is off.',
    bio: 'A wizard of tremendous power and terrible spelling. Has failed the Grand Spelling Exam forty times.',
    lines: {
      greet: [
        'Salutations! I cast a spell of greeting. Hello! See? It worked.',
        'Good evening! Or morning. Time is an illusion. Dinner is not.',
        'Fizzlewick, reporting for... supper.',
      ],
      order: [
        'One {recipe}, please! I’d conjure it myself, but last time I conjured a sofa.',
        'I’ll have the {recipe}. Spelled correctly, if possible.',
        'A {recipe}! That’s F-I-Z... no, wait. Just the {recipe}.',
      ],
      happy: [
        'Splendid! You spell beautifully. With food!',
        'Marvellous! And no sofas at all!',
        'Delicious! Ten wizard points to you. They’re worth nothing.',
      ],
      grumpy: [
        'I’ve waited so long I nearly cast a spell. Nobody wants that.',
        'Tick tock, as my enchanted clock says. It also says “bananas”, sometimes.',
        'My beard is getting longer. That’s not a spell. That’s time.',
      ],
      waiting: ['*mutters* I before E, except after... hmm.', 'Fireball has two L’s. Or three?', '*accidentally turns a spoon into a smaller spoon*'],
      banter: [
        'I passed! Now I’m studying for the Advanced Exam. Silent letters. Terrifying.',
        'I taught Barley to levitate. Briefly. He did not enjoy it.',
        'Examiner Grimsby still catches flies with his tongue. We don’t mention it.',
      ],
    },
    story: [
      {
        title: 'A Slight Mishap',
        arrive: [
          g('Ahem! Fizzlewick the Befuddled. Wizard. Former wizard. Future wizard. It’s complicated.'),
          g('I tried to cast FIREBALL on the way here, but I spelled it wrong.', 'sad'),
          b('What happened?'),
          g('I cast FIRE BALL. There’s now a very warm dance in the town square.'),
        ],
        order: 'Please, a {recipe}. My magic needs a snack.',
        done: [
          g('Thank you! You spell beautifully. With food! Most unusual.', 'happy'),
          g('I have an exam soon. The Grand Spelling Exam. Forty-first attempt.'),
        ],
        reward: { coins: 30 },
      },
      {
        title: 'Study Buddy',
        arrive: [
          g('Would you quiz me? Spell “LEVITATE”.', 'happy'),
          b('Don’t. Last time he levitated me into the chimney.'),
          g('L-E-V-I-T... T-A-T-E. Oh dear. My hat is in a tree now.', 'surprised'),
        ],
        order: 'A {recipe}, please. And perhaps a ladder.',
        done: [g('Practice makes perfect! Or at least, practice makes... practice.')],
        reward: { coins: 40 },
      },
      {
        title: 'The Frog Incident',
        arrive: [
          g('Small problem. I tried to cast CHARM on the examiner.', 'sad'),
          g('I spelled it with an F.'),
          b('...FHARM?'),
          g('He’s a frog now. Temporarily! Mostly temporarily.'),
          b('Is that a frog in your pocket?'),
          g('Say hello, Examiner Grimsby.'),
        ],
        order: 'One {recipe}. He’s not hungry. He’s furious.',
        done: [g('He’ll turn back by Tuesday. Probably. The exam is rescheduled, anyway.')],
        reward: { coins: 50 },
      },
      {
        title: 'Cramming',
        arrive: [
          g('The exam is tomorrow. I’ve been studying your menu. It’s full of excellent words.', 'happy'),
          g('“Stew.” Four letters. No silent letters. No surprises. A perfect word.'),
          b('And a perfect meal. Unlike your spells.'),
        ],
        order: 'Brain food, please. A {recipe}.',
        done: [g('Wish me luck! And if a frog comes in asking for revenge... I wasn’t here.')],
        reward: { coins: 60 },
      },
      {
        title: 'Passed!',
        arrive: [
          g('I PASSED! Forty-first time lucky!', 'happy'),
          g('The final word was “TAVERN”. I thought of you and spelled it perfectly.'),
          b('And the examiner?'),
          g('Human again. Mostly. He still catches flies. We don’t mention it.'),
          g('Take my old spellbook. The misspelled spells are crossed out. It’s a very thin book now.'),
        ],
        order: 'A celebratory {recipe}!',
        done: [g('To spelling! To friendship! To only mildly dangerous magic!', 'happy')],
        reward: { coins: 100, furniture: 'fizzlewick-grimoire' },
      },
    ],
  },

  // ════════════════════════════════════════════════════════════════════════
  {
    id: 'pip',
    name: 'Pip Quickfinger',
    title: 'Goblin Merchant (and Squeak)',
    portrait: {
      species: 'goblin',
      skin: '#7fb069',
      hair: '#3a2e2a',
      hairStyle: 'wild',
      hat: 'cap',
      hatColor: '#a0522d',
      hatAccent: '#d9a441',
      outfit: '#c47a2c',
      outfitAccent: '#6b4226',
      nose: 'long',
      eyes: 'wide',
      accessories: ['rat', 'earring'],
    },
    favorites: ['goblin-goulash', 'cheese-board'],
    patienceMult: 0.9,
    tipMult: 0.8,
    unlock: { level: 3 },
    rumor: 'Somebody in town is selling “genuine dragon eggs”. They look a lot like potatoes.',
    bio: 'A goblin merchant with a heart of gold (possibly fool’s gold) and a rat named Squeak who handles the accounts.',
    lines: {
      greet: [
        'Psst! Pip Quickfinger, purveyor of fine goods. Mostly fine. Some goods.',
        'Evening, boss! Squeak says hello. He said it in Rat, so you missed it.',
        'Pip’s here! Hide nothing! I’ll find it anyway! ...Kidding!',
      ],
      order: [
        'One {recipe}! I’ll pay in real coins. Squeak checked.',
        'A {recipe}, please. Squeak gets the crumbs.',
        'Gimme a {recipe}! Best deal in town, this place.',
      ],
      happy: [
        'Top quality! I could sell this for double. Can I? No? Fair.',
        'Squeak approves! He’s very picky. He eats paper.',
        'Lovely! Five stars. Six if you count Squeak’s.',
      ],
      grumpy: [
        'Time is money, boss! And I’m losing both.',
        'Squeak’s getting grumpy. He bites when he’s grumpy. So do I, honestly.',
        'I could’ve sold three bridges by now.',
      ],
      waiting: ['*Squeak nibbles the menu*', 'Wanna buy a treasure map? It leads here. The treasure is you!', '*jingles pockets suspiciously*'],
      banter: [
        'The egg hatched, eh? Told you it was genuine. I’m as surprised as you are.',
        'Squeak opened a savings account. He’s richer than me now.',
        'New stock! Invisible swords. Very hard to prove they’re not there.',
      ],
    },
    story: [
      {
        title: 'Dragon Eggs, Cheap!',
        arrive: [
          g('Psst! Wordsmith! Want a genuine dragon egg? Only fifty coins!', 'happy'),
          b('That’s a potato.'),
          g('It’s a very... potato-shaped egg.'),
          b('It has a sprout.'),
          g('Dragons sprout. Everybody knows that.'),
        ],
        order: 'Think it over with a {recipe}. My treat! You pay.',
        done: [g('No deal? Fair enough. Squeak says you’ve got a good eye. Squeak’s never wrong. He’s a rat.')],
        reward: { coins: 30 },
      },
      {
        title: 'The Invisible Sword',
        arrive: [
          g('New stock, boss! The Invisible Sword. Sharpest blade in the land!', 'happy'),
          b('Your hands are empty.'),
          g('That’s how invisible it is. Incredible craftsmanship.'),
          g('...Squeak says I should stop selling invisible things. He’s getting soft.', 'sad'),
        ],
        order: 'A {recipe}, please. Visible, preferably.',
        done: [g('Maybe I’ll try selling real stuff. Squeak’s idea. He’s full of ideas. And crumbs.')],
        reward: { coins: 40 },
      },
      {
        title: 'Honest Pip',
        arrive: [
          g('I was an honest merchant for a whole day!', 'happy'),
          g('Sold one sock. A real sock. It had a hole in it, and I TOLD the buyer about the hole.'),
          b('Proud of you.'),
          g('Made two coppers. Squeak says it’s a start. I say it’s a sock.'),
        ],
        order: 'Celebrate with me! A {recipe}!',
        done: [g('Honesty feels weird. Like wearing shoes on the correct feet.')],
        reward: { coins: 50 },
      },
      {
        title: 'The Egg Is Warm',
        arrive: [
          g('Boss. Remember the potato egg?', 'surprised'),
          g('It’s warm. And it’s... ticking? No. Humming. It’s humming.'),
          b('Potatoes don’t hum.'),
          g('THAT’S WHAT I SAID. Squeak is hiding in my hat.'),
        ],
        order: 'A {recipe} for my nerves, please!',
        done: [g('What if it’s actually a... No. No way. I buy my eggs from a farmer named Doug.')],
        reward: { coins: 60 },
      },
      {
        title: 'It Hatched',
        arrive: [
          g('IT HATCHED! IT’S A DRAGON! A TINY ONE!', 'surprised'),
          g('Doug’s farm is at the foot of Mount Grumble. In hindsight, that was a clue.'),
          b('A real dragon egg, sold as a potato, by a goblin who thought he was lying.'),
          g('I can’t keep her. Squeak’s terrified. Will you look after her? She likes warm places and shiny things.'),
          g('Genuine article. No refunds.', 'happy'),
        ],
        order: 'One {recipe} to celebrate. And a tiny bowl for her!',
        done: [g('Best deal I ever made, and I didn’t even make money. Weird feeling. Nice, though.', 'happy')],
        reward: { coins: 80, furniture: 'hatchling-nest' },
      },
    ],
  },

  // ════════════════════════════════════════════════════════════════════════
  {
    id: 'reginald',
    name: 'Sir Reginald Pompington III',
    title: 'Knight Errant',
    portrait: {
      species: 'human',
      skin: '#f3c9a5',
      hair: '#e9c46a',
      hairStyle: 'short',
      beard: 'mustache',
      hat: 'helmet',
      hatColor: '#b8c2cc',
      hatAccent: '#2f5fa7',
      outfit: '#9aa6b2',
      outfitAccent: '#2f5fa7',
      nose: 'big',
      eyes: 'dot',
      accessories: ['blush'],
    },
    favorites: ['royal-feast', 'knightly-kebab', 'roast-boar'],
    patienceMult: 1,
    tipMult: 1.2,
    unlock: { level: 3, furniture: 'notice-board' },
    rumor: 'A knight is looking for somewhere to pin his quest notices. A notice board might catch his eye.',
    bio: 'A noble knight on a quest for the Holy Grail. His quest scroll fell in a puddle, so he follows the smudged bits.',
    lines: {
      greet: [
        'Hark! Sir Reginald Pompington the Third approaches! The first two were my father and grandfather.',
        'Well met, noble barkeep! My armour and I require refreshment.',
        'Tally-ho! What a splendid establishment. Hardly any dragons.',
      ],
      order: [
        'A {recipe}, good Wordsmith! For honour! And for dinner!',
        'I shall have the {recipe}. Knight-sized, if you please.',
        'One {recipe}! My horse will wait outside. He’s used to it.',
      ],
      happy: [
        'Huzzah! A feast fit for a knight! Which I am!',
        'Magnificent! You shall appear in my chronicles. Chapter nine, probably.',
        'By my moustache! Delicious!',
      ],
      grumpy: [
        'A knight must be patient. This knight is running low.',
        'I have besieged castles quicker than this.',
        'My armour is starting to squeak with impatience.',
      ],
      waiting: ['*polishes sword on a napkin*', '*clanks nervously*', 'Is it ready? I ask as a knight. Also as a hungry man.'],
      banter: [
        'The Holy Grill has found its noble purpose: kebabs.',
        'My horse sends his regards. He is also eating your window box.',
        'I’m considering a new quest. Something with clearer handwriting.',
      ],
    },
    story: [
      {
        title: 'A Soggy Scroll',
        arrive: [
          g('Good barkeep! I am on a sacred quest for the Holy GRAIL!', 'happy'),
          g('Alas, my quest scroll fell in a puddle. Some of the letters have... wandered.'),
          b('Let’s see. It says “Seek the Holy R-A-I-L”.'),
          g('A holy RAIL! Of course! To the fence-maker!', 'surprised'),
        ],
        order: 'But first, a {recipe}! Questing is hungry work.',
        done: [g('Onward! Fences await!', 'happy')],
        reward: { coins: 30 },
      },
      {
        title: 'The Holy Rail',
        arrive: [
          g('I found it! The Holy Rail!', 'happy'),
          g('It’s... a fence post. The priest said it has been blessed. Twice.'),
          b('Maybe read the scroll again?'),
          g('Hmm. Now it looks like “Seek the Holy G-A-I-L”.', 'surprised'),
        ],
        order: 'A {recipe}, while I ponder!',
        done: [g('To find this Gail! Tally-ho!')],
        reward: { coins: 40 },
      },
      {
        title: 'The Holy Gail',
        arrive: [
          g('I found Gail.'),
          g('She is a very nice lady who runs a bakery. She was quite confused. Then quite annoyed.', 'sad'),
          b('Did she give you anything?'),
          g('A loaf of bread and a firm request to never come back.'),
        ],
        order: 'A {recipe}. My honour is wounded, but my appetite is not.',
        done: [
          g('Wait! If I squint... “Seek the Holy G-R-I-L-L”!', 'surprised'),
          b('That’s... actually plausible.'),
        ],
        reward: { coins: 50 },
      },
      {
        title: 'Grill Hunting',
        arrive: [
          g('Legend speaks of a grill forged by the first cook, lost in the Caverns of Crumb.', 'happy'),
          g('I shall need courage, a torch, and a very long spatula.'),
          b('Do knights use spatulas?'),
          g('This one does. Fear my flipping.'),
        ],
        order: 'A {recipe} for the journey!',
        done: [g('Farewell! If I do not return, tell my horse... he was a good horse.')],
        reward: { coins: 60 },
      },
      {
        title: 'The Holy Grill',
        arrive: [
          g('BEHOLD! The Holy Grill!', 'happy'),
          g('Radiant! Ancient! Slightly greasy!'),
          b('So the Grail was a Grill all along?'),
          g('Who’s to say? Perhaps the real Grail was the kebabs we made along the way.'),
          g('I bequeath it to the finest kitchen in the land. Yours! Along with my recipe for Knightly Kebabs.'),
        ],
        order: 'Let us christen it! A {recipe}!',
        done: [g('My quest is complete! What does one do after a quest? Lunch, I suppose. Daily.', 'happy')],
        reward: { coins: 80, furniture: 'holy-grill', recipe: 'knightly-kebab' },
      },
    ],
  },

  // ════════════════════════════════════════════════════════════════════════
  {
    id: 'oakley',
    name: 'Old Oakley',
    title: 'Ancient Ent',
    portrait: {
      species: 'ent',
      skin: '#8a6440',
      hair: '#5f8f3e',
      beard: 'long',
      outfit: '#6b4a2e',
      outfitAccent: '#5f8f3e',
      nose: 'long',
      eyes: 'sleepy',
      accessories: ['leaves'],
    },
    favorites: ['barkroot-tea', 'mushroom-pie'],
    patienceMult: 1.6,
    tipMult: 0.9,
    unlock: { level: 4, furniture: 'potted-fern' },
    rumor: 'Something tall and leafy has been pacing (very slowly) outside town. It likes ferns.',
    bio: 'An ancient tree-person who speaks... very... slowly. Has been searching for his lost acorn for two hundred years.',
    lines: {
      greet: [
        'Hmmm... hoom... good... evening... little... Wordsmith.',
        'Hoom. I came... as quickly... as I could. Is it... Tuesday?',
        'Ah... the tavern... Hmm. It has... grown.',
      ],
      order: [
        'I would... like... hmm... a {recipe}... No rush.',
        'One... {recipe}... Take your... time... I have... centuries.',
        'Hmm... hoom... {recipe}.',
      ],
      happy: [
        'Hoom, hoom... delicious. I will tell... the forest... in a decade... or so.',
        'Splendid... that was... fast... too fast... perhaps.',
        'Hmm... a fine... meal. My roots... are happy.',
      ],
      grumpy: [
        'Hoom... even I... am getting... hungry.',
        'I have waited... for rain... less long... than this.',
        'Hmm... I have started... to grow... moss.',
      ],
      waiting: ['Hmm... hoom...', '*a leaf drifts gently down from Oakley’s head*', 'Did I... order? Hoom... I believe... I did.'],
      banter: [
        'Hoom... the sapling grows. Her first word... was “photosynthesis”.',
        'Barley... is very... loud... for a cup.',
        'I met... a squirrel... today. We talked... for a week.',
      ],
    },
    story: [
      {
        title: 'Hoom',
        arrive: [
          g('Hmmm... hoom... Hello... I am... Oakley.'),
          b('...And?'),
          g('Patience... little cup... I am... getting there.'),
          g('I am looking... for my acorn. She rolled away... two hundred... years ago.', 'sad'),
        ],
        order: 'May I have... a {recipe}... please...',
        done: [g('Thank you... I will search... the next valley. It will take... a while.')],
        reward: { coins: 40 },
      },
      {
        title: 'Clues',
        arrive: [
          g('Hoom... the squirrels... have seen... an acorn... that talks.', 'surprised'),
          b('A talking acorn. Sure. Why not. I’m a talking cup.'),
          g('They say... she went to town... to become... a pot plant.'),
        ],
        order: 'A {recipe}... to fuel... the search.',
        done: [g('Hmm... pot plants... live in taverns... do they not?')],
        reward: { coins: 50 },
      },
      {
        title: 'The Fern',
        arrive: [
          g('Hoom... your fern... is my cousin.', 'happy'),
          g('Twice removed... once replanted. She says... hello.'),
          b('The fern talks too?!', 'surprised'),
          g('Everything talks... little cup. Few... listen.'),
        ],
        order: 'A {recipe}... and some water... for my cousin.',
        done: [g('She says... she saw my acorn... in the market square. Hmm... hoom.')],
        reward: { coins: 60 },
      },
      {
        title: 'Market Day',
        arrive: [
          g('Hoom... I went... to the market.', 'sad'),
          g('It took me... three days... to cross the square. People kept... hanging washing... on me.'),
          b('Any luck?'),
          g('A goblin... said he sold her... long ago... as a “magic bean”.'),
          b('Oh, Pip.'),
        ],
        order: 'A {recipe}... please. I must think... slowly... about this.',
        done: [g('The buyer... lives near here. I can feel it... in my roots.')],
        reward: { coins: 70 },
      },
      {
        title: 'Found',
        arrive: [
          g('HOOM!', 'happy'),
          b('That was fast! For you.'),
          g('She was here... all along. Under your... floorboards. A sapling... now.'),
          g('She wants... to stay. She likes... the music... the warmth... and the loud cup.'),
          b('...She likes me?', 'surprised'),
          g('Look after her... I will visit... every decade... Every week, I mean. Hoom.'),
        ],
        order: 'A celebration... {recipe}... hoom!',
        done: [g('Two hundred years... worth... every second. Hmm... hoom.', 'happy')],
        reward: { coins: 100, furniture: 'oakley-sapling' },
      },
    ],
  },

  // ════════════════════════════════════════════════════════════════════════
  {
    id: 'mortimer',
    name: 'Mortimer Gloom',
    title: 'Nervous Necromancer',
    portrait: {
      species: 'human',
      skin: '#e6ddd3',
      hair: '#1c1c24',
      hairStyle: 'long',
      hat: 'hood',
      hatColor: '#2d2438',
      hatAccent: '#7d5ba6',
      outfit: '#241e2e',
      outfitAccent: '#7d5ba6',
      nose: 'pointy',
      eyes: 'sleepy',
      accessories: ['necklace'],
    },
    favorites: ['calcium-shake', 'mushroom-pie'],
    patienceMult: 1.2,
    tipMult: 1,
    unlock: { level: 5 },
    rumor: 'A shy young man and a very polite skeleton have been seen peeking through the window.',
    bio: 'A necromancer with anxiety, a skeleton named Bones, and a deep wish for friends with pulses.',
    lines: {
      greet: [
        'H-hello. It’s Mortimer. Bones says hi. He has no lungs, so it’s more of a rattle.',
        'Good evening! Don’t mind Bones. He’s harmless. He’s barely even there.',
        'It’s me again. Mortimer. The necromancer. The nice one.',
      ],
      order: [
        'One {recipe}, please. And a straw for Bones. He likes to pretend.',
        'Could I trouble you for a {recipe}? Only if it’s no trouble. Is it trouble?',
        'A {recipe}, please! Bones will just watch. He’s a good watcher.',
      ],
      happy: [
        'Oh, that’s lovely. Bones says it’s lovely too. He can’t taste, but he’s supportive.',
        'Wonderful! You’re kinder than most people I’ve dug up.',
        'The nicest thing that’s happened to me all week. Including the ghost.',
      ],
      grumpy: [
        'It’s fine. I’m used to waiting. I used to wait in crypts. For fun.',
        'Bones is tapping his foot. Loudly. He’s mostly foot.',
        'I’m not upset! I’m just... gloomy. It’s my surname.',
      ],
      waiting: ['*Bones rattles softly*', 'Sorry, is Bones in the way? He gets everywhere.', 'Do you have a quiet table? Near the back? Not too near. Crypt vibes.'],
      banter: [
        'Book club is going well! Bones only brought one skull-themed book this time.',
        'I made a friend with a pulse! Gail, from the bakery. She’s very forgiving.',
        'Bones loves his job at the theatre. Best coat rack they’ve ever had.',
      ],
    },
    story: [
      {
        title: 'Meet Bones',
        arrive: [
          g('Um. Hello. I’m Mortimer. I’m a necromancer. Please don’t scream.', 'sad'),
          b('I’m a talking tankard. We’re all weird here.'),
          g('Oh! Oh good. This is Bones. He’s my best friend. My only friend. He’s a skeleton.', 'happy'),
        ],
        order: 'One {recipe}, please. Bones can’t eat, but he likes to be included.',
        done: [
          g('It went straight through him. As usual. But he looked so happy.', 'happy'),
          g('Well. He always looks like that. It’s the teeth.'),
        ],
        reward: { coins: 40 },
      },
      {
        title: 'Small Talk',
        arrive: [
          g('I’ve been practising conversation. I read a book: “How to Make Friends and Not Raise the Dead”.'),
          g('Chapter one: don’t open with “I can talk to your ancestors”.'),
          b('Solid advice.'),
        ],
        order: 'A {recipe}, please. And... how was your day? Did I do that right?',
        done: [g('I did it! Small talk! I feel like I raised a whole cemetery. In a good way.', 'happy')],
        reward: { coins: 50 },
      },
      {
        title: 'The Party',
        arrive: [
          g('I threw a party!', 'happy'),
          g('Eleven guests came. Ten were skeletons. But one was Gail, from the bakery!'),
          b('Gail from the bakery? Lovely woman. Terrifying scones.'),
          g('She said she’s had a very strange month. Something about a knight. She wouldn’t elaborate.'),
        ],
        order: 'A celebratory {recipe}, please!',
        done: [g('Next time I’ll invite only people with skin. Baby steps.')],
        reward: { coins: 60 },
      },
      {
        title: 'Bones Runs Away',
        arrive: [
          g('Bones is gone!', 'sad'),
          g('He left a note. Well, a finger bone pointing at the door. Very dramatic.'),
          b('Maybe he needs some independence?'),
          g('He’s four hundred years old. He’s allowed. But I miss him.'),
        ],
        order: 'A {recipe}. The sad kind. Is there a sad kind?',
        done: [g('If you see a skeleton looking for work, be kind. He’s bad at interviews. He just grins.')],
        reward: { coins: 70 },
      },
      {
        title: 'Book Club',
        arrive: [
          g('Bones came back! He got a job as a coat rack at the theatre. He loves it!', 'happy'),
          g('And I realised... I have friends now. You. Barley. Gail. Even Fizzlewick, who keeps turning me into a newt.'),
          b('We’re very fond of you, Mort.'),
          g('I’d like to start a book club here. I built a reading nook for it. No bones in it. Promise.'),
        ],
        order: 'One {recipe} for the first meeting!',
        done: [g('The first book is about friendship. Bones picked it. He’s surprisingly sentimental.', 'happy')],
        reward: { coins: 90, furniture: 'reading-nook' },
      },
    ],
  },

  // ════════════════════════════════════════════════════════════════════════
  {
    id: 'zephyrine',
    name: 'Madame Zephyrine',
    title: 'Fortune Teller',
    portrait: {
      species: 'human',
      skin: '#8d5a3b',
      hair: '#2b1b17',
      hairStyle: 'long',
      hat: 'scarf',
      hatColor: '#7b2d8b',
      hatAccent: '#f2c14e',
      outfit: '#2a6f73',
      outfitAccent: '#f2c14e',
      nose: 'button',
      eyes: 'sleepy',
      accessories: ['earring', 'necklace'],
    },
    favorites: ['moonberry-tart', 'barkroot-tea', 'honey-mead'],
    patienceMult: 1,
    tipMult: 1.2,
    unlock: { level: 5, furniture: 'crystal-ball' },
    rumor: 'A mysterious fortune teller visits only places with a crystal ball. She says she saw it coming.',
    bio: 'A fortune teller whose predictions are always accurate, just never in the way anyone expects.',
    lines: {
      greet: [
        'I knew you would say hello. Hello.',
        'Madame Zephyrine sees all. Including that stain on your apron.',
        'The spirits told me to come here tonight. Also, I was hungry.',
      ],
      order: [
        'The cards say I will order a {recipe}. Who am I to argue with the cards?',
        'I foresee... a {recipe}. In my immediate future. Please.',
        'A {recipe}. I saw it in a vision. It was delicious.',
      ],
      happy: [
        'Exactly as I predicted. Only better.',
        'The spirits are pleased. So is my stomach.',
        'I foresee a five-star review. Oh look, it’s mine.',
      ],
      grumpy: [
        'I foresaw a wait. I did not foresee THIS wait.',
        'The crystal ball is fogging up. That’s me. Sighing.',
        'The cards say “hurry”. So do I.',
      ],
      waiting: ['*gazes meaningfully into a spoon*', 'I sense... a delay.', 'Your future holds... cooking. Specifically, right now.'],
      banter: [
        'I foresee you will enjoy this conversation. Too late now if you don’t.',
        'Barley’s future is bright. Also foamy.',
        'The cards predict rain. Or a spilled ale. The cards are vague about liquids.',
      ],
    },
    story: [
      {
        title: 'A Vision',
        arrive: [
          g('Madame Zephyrine. I have come because of a vision.'),
          g('I saw a tavern. A great fire. A thousand guests. And a tankard that never stops talking.'),
          b('Rude. But accurate.'),
        ],
        order: 'The vision also included a {recipe}. Let us honour it.',
        done: [g('The fire, the guests... it will come to pass. Mark my words. Well, mark my vowels.')],
        reward: { coins: 40 },
      },
      {
        title: 'Beware the Goose',
        arrive: [
          g('Wordsmith. Beware the goose.', 'surprised'),
          b('What goose?'),
          g('The spirits did not specify. They seldom specify. Spirits are terrible with details.'),
        ],
        order: 'A {recipe}, please. To calm the spirits.',
        done: [g('Remember: the goose. Always the goose.')],
        reward: { coins: 50 },
      },
      {
        title: 'The Cracked Ball',
        arrive: [
          g('Disaster. My crystal ball has cracked.', 'sad'),
          g('Every prediction now comes out in two halves. “You will meet a tall... sandwich.”'),
          b('Honestly? I’d like to meet a tall sandwich.'),
        ],
        order: 'A {recipe}. I cannot see the future on an empty stomach.',
        done: [g('Wait... the cracks... they spell something. T-A-V-E-R-N. Something big is coming here.', 'surprised')],
        reward: { coins: 60 },
      },
      {
        title: 'Wings on the Horizon',
        arrive: [
          g('The spirits are restless. They speak of wings. And snacks.', 'surprised'),
          g('Large wings. Enormous snacks.'),
          b('That’s either a dragon or a very ambitious pigeon.'),
        ],
        order: 'A {recipe}, quickly. The spirits say you’ll need the practice.',
        done: [g('When the great fire comes, do not be afraid. Be... well stocked.')],
        reward: { coins: 70 },
      },
      {
        title: 'The Goose Explained',
        arrive: [
          g('I understand now! The goose!', 'happy'),
          g('The goose was my great-great-grandmother’s. She predicted the future too. By honking.'),
          b('So the goose was a prophet?'),
          g('The goose was EVERYTHING. These lanterns were hers. They twinkle before good news. Take them.'),
        ],
        order: 'One last {recipe}, as foreseen!',
        done: [g('I foresee we’ll be friends for a very long time. And I’m never wrong. Except about the sandwich.', 'happy')],
        reward: { coins: 90, furniture: 'lights-stars' },
      },
    ],
  },

  // ════════════════════════════════════════════════════════════════════════
  {
    id: 'brinebottom',
    name: 'Captain Brinebottom',
    title: 'Retired Pirate',
    portrait: {
      species: 'human',
      skin: '#c98b5e',
      hair: '#9e9e9e',
      hairStyle: 'short',
      beard: 'long',
      hat: 'tricorn',
      hatColor: '#2b2b2b',
      hatAccent: '#e0b44a',
      outfit: '#a4262c',
      outfitAccent: '#e0b44a',
      nose: 'big',
      eyes: 'dot',
      accessories: ['eyepatch', 'earring', 'scar'],
    },
    favorites: ['sea-salt-grog', 'fish-chowder'],
    patienceMult: 1,
    tipMult: 1.3,
    unlock: { level: 6, furniture: 'ship-bottle' },
    rumor: 'An old sea dog is looking for a tavern with a proper nautical touch. A ship in a bottle, perhaps.',
    bio: 'A retired pirate whose tales grow taller with every tankard. Once fought a kraken “bigger than a mountain. Two mountains.”',
    lines: {
      greet: [
        'Ahoy, landlubber! Cap’n Brinebottom, terror of the seven seas! Retired terror.',
        'Arr! The sea’s calm, the ale’s cold, and life is good.',
        'Ahoy! Did I ever tell ye about the kraken? Sit down. It’s a long one.',
      ],
      order: [
        'A {recipe}, and be quick about it! Arr! ...Please.',
        'A {recipe} for the Cap’n! Extra salty, like me temper.',
        'One {recipe}! I’d pay in doubloons, but they’re chocolate.',
      ],
      happy: [
        'Shiver me timbers, that’s fine grub!',
        'Arr! Better than ship’s biscuit! Those could sink a ship. One did.',
        'Ye’d make a fine ship’s cook! Ye’re hired! Ye’re not hired. I don’t have a ship.',
      ],
      grumpy: [
        'I’ve been becalmed shorter than this!',
        'Arr... me patience is walkin’ the plank.',
        'I’ve waited so long me wooden leg got hungry. I don’t even have a wooden leg.',
      ],
      waiting: ['*hums a sea shanty, off-key*', 'The kraken was THIS big. *gestures wider than the room*', 'Arr. Arr. ...Arr.'],
      banter: [
        'Gerald sends his love. He’s learned to juggle. Eight balls at once, the show-off.',
        'I’m writing me memoirs: “Mostly True Tales of the Sea”.',
        'The sea keeps calling. I let it go to voicemail.',
      ],
    },
    story: [
      {
        title: 'Ahoy',
        arrive: [
          g('Arr! Cap’n Brinebottom! I once fought a kraken as big as a HOUSE!', 'happy'),
          b('A house. Impressive.'),
          g('Aye! A small house. A cottage. But a proud cottage.'),
        ],
        order: 'A {recipe}, landlubber!',
        done: [g('Next time I’ll tell ye how I escaped. It involves a spoon.')],
        reward: { coins: 40 },
      },
      {
        title: 'Bigger',
        arrive: [
          g('So there I was, face to face with the kraken. Big as a CASTLE!', 'surprised'),
          b('Last week it was a cottage.'),
          g('It had a growth spurt! Krakens do that.'),
          g('I fought it off with nothing but a spoon and me charming personality.'),
        ],
        order: 'A {recipe}, and don’t rush me story.',
        done: [g('The spoon was silver. Krakens hate silver. And puns. I used both.', 'happy')],
        reward: { coins: 50 },
      },
      {
        title: 'Even Bigger',
        arrive: [
          g('Now the kraken, as I recall, was the size of a MOUNTAIN. Two mountains!', 'happy'),
          b('It’s grown again.'),
          g('...In truth, I can’t quite remember how big it was. I was very young. It was very dark.', 'sad'),
        ],
        order: 'A {recipe}, please. I’m feelin’ nostalgic.',
        done: [g('I wonder what happened to the old beastie. We parted on... confusing terms.')],
        reward: { coins: 60 },
      },
      {
        title: 'A Letter',
        arrive: [
          g('I got a letter! Written in ink. Octopus ink.', 'surprised'),
          g('It says: “Dear Captain. Sorry about the spoon thing. Can we talk? — G.”'),
          b('G?'),
          g('Gerald! The kraken’s name was Gerald! It’s all comin’ back!', 'happy'),
        ],
        order: 'A {recipe}. Me heart’s all at sea.',
        done: [g('I’ve invited him here. Hope that’s alright. He’s... not as big as I said.')],
        reward: { coins: 70 },
      },
      {
        title: 'Gerald',
        arrive: [
          g('Wordsmith, meet Gerald! The terrifying kraken!', 'happy'),
          b('He’s the size of a teacup.'),
          g('He was a baby back then. So was I, practically. We were both scared. I dropped me spoon on him.'),
          g('He’s forgiven me! We’re starting a business. Sea tours. He does the tentacle waving.'),
          g('Take me old ship’s wheel. Every tavern needs a captain’s touch.'),
        ],
        order: 'A {recipe} for me, and a thimble of ale for Gerald!',
        done: [g('Best friends after forty years. The sea is strange, but friendship’s stranger. Arr.', 'happy')],
        reward: { coins: 100, furniture: 'ships-wheel' },
      },
    ],
  },

  // ════════════════════════════════════════════════════════════════════════
  {
    id: 'ledgerly',
    name: 'Ledgerly Pinchpenny',
    title: 'Royal Tax Inspector',
    portrait: {
      species: 'gnome',
      skin: '#f2b8a0',
      hair: '#f5f5f5',
      hairStyle: 'short',
      beard: 'mustache',
      hat: 'tophat',
      hatColor: '#2a2a2e',
      hatAccent: '#8b1e2d',
      outfit: '#5a5f6b',
      outfitAccent: '#8b1e2d',
      nose: 'big',
      eyes: 'dot',
      accessories: ['monocle'],
    },
    favorites: ['buttered-bread', 'cheese-board', 'royal-feast'],
    patienceMult: 0.9,
    tipMult: 0.7,
    unlock: { level: 8, furniture: 'brass-register' },
    rumor: 'The Royal Tax Office takes an interest in any tavern with a brass register. Ka-ching.',
    bio: 'His Majesty’s Inspector of Taverns, Taxes and Tomfoolery. Loves rules. Secretly loves stew more.',
    lines: {
      greet: [
        'Ledgerly Pinchpenny, Inspector of Taverns. This is an official visit. And an unofficial dinner.',
        'Good evening. I am here to inspect. Mostly the menu.',
        'Pinchpenny. Inspector. Hungry. In that order. Actually, reverse that order.',
      ],
      order: [
        'One {recipe}, itemised, with receipt.',
        'A {recipe}, please. For inspection purposes. Thorough inspection.',
        'A {recipe}. Form 27-B, in triplicate. That was a joke. I never joke.',
      ],
      happy: [
        'Hmm. Satisfactory. Very satisfactory. Suspiciously satisfactory.',
        'I shall note this in my report under “Delicious”.',
        'Exceptional. Don’t tell anyone I said exceptional.',
      ],
      grumpy: [
        'Tardiness noted. In ink.',
        'I’ve filled out three forms while waiting. For fun.',
        'Regulations permit a reasonable wait. This is slightly unreasonable.',
      ],
      waiting: ['*scribbles in a tiny notebook*', '*measures the counter with a tiny ruler*', 'Is that tankard licensed to talk?'],
      banter: [
        'I’ve approved your tavern for another year. And the next. I’ve pre-approved the century.',
        'Barley’s talking licence is in order. I made him one myself.',
        'I’ve started taking Tuesdays off. Radical, I know.',
      ],
    },
    story: [
      {
        title: 'Official Business',
        arrive: [
          g('Ledgerly Pinchpenny, Royal Inspector. I am here to inspect your tavern.', 'grumpy'),
          g('Item one: a tankard is talking. Is it licensed?'),
          b('I’m three hundred years old. I predate licences.'),
          g('Noted. Suspiciously.'),
        ],
        order: 'I will now inspect a {recipe}. Thoroughly.',
        done: [g('Hmm. The food passes. Provisionally. I shall return.')],
        reward: { coins: 50 },
      },
      {
        title: 'Paperwork',
        arrive: [
          g('I have brought forms. Twelve forms. One of them is about forms.'),
          b('What’s the form about forms for?'),
          g('To request more forms. Obviously.'),
        ],
        order: 'A {recipe}, while you fill these out. In triplicate.',
        done: [g('...Perfectly completed. Nobody completes them perfectly. I don’t know how to feel.', 'surprised')],
        reward: { coins: 60 },
      },
      {
        title: 'Off the Record',
        arrive: [
          g('This visit is... off the record.', 'sad'),
          g('I never eat anywhere twice. Rules. No favouritism. But I keep thinking about your cooking.'),
          b('Are you... enjoying yourself, Inspector?'),
          g('I don’t know. It’s never happened before.'),
        ],
        order: 'A {recipe}. Unofficially.',
        done: [g('That was... nice. I shall have to file a report about how nice it was.', 'happy')],
        reward: { coins: 70 },
      },
      {
        title: 'A Complaint',
        arrive: [
          g('Someone has filed a complaint about you!', 'grumpy'),
          g('It says: “Tavern too cosy. Nobody wants to leave. Town productivity down forty percent.”'),
          b('Who filed it?'),
          g('...I did. Last month. Before I’d eaten here. I’m withdrawing it. That requires four more forms.'),
        ],
        order: 'A {recipe}. I need strength for the paperwork.',
        done: [g('Complaint withdrawn. Righteousness restored. Stomach full.', 'happy')],
        reward: { coins: 80 },
      },
      {
        title: 'Royal Seal',
        arrive: [
          g('Wordsmith, I bring news from the capital.', 'happy'),
          g('By royal decree, your tavern is awarded the Royal Seal of Excellence.'),
          b('Who recommended us?'),
          g('An anonymous inspector. Very handsome. Excellent moustache.'),
        ],
        order: 'One celebratory {recipe}. With a tip. A large tip. I’m feeling reckless.',
        done: [g('Same time next week? I’ve put it in my calendar. In ink.', 'happy')],
        reward: { coins: 150, furniture: 'royal-seal' },
      },
    ],
  },

  // ════════════════════════════════════════════════════════════════════════
  {
    id: 'ember',
    name: 'Ember',
    title: 'Very Polite Dragon',
    portrait: {
      species: 'dragon',
      skin: '#d9542b',
      outfit: '#b53d1e',
      outfitAccent: '#f2b36b',
      eyes: 'wide',
    },
    favorites: ['dragon-chili', 'roast-boar'],
    patienceMult: 0.8,
    tipMult: 2,
    unlock: { level: 9, afterStoryOf: 'barnaby' },
    rumor: 'Barnaby’s ballad has an admirer with wings. Finish his story, grow your fame, and she may visit.',
    bio: 'A dragon of impeccable manners and enormous appetite. Adores bad poetry, especially Barnaby’s.',
    lines: {
      greet: [
        'Good evening! Don’t mind me, I’ll duck. I always duck.',
        'Hello, darling! I’ve parked on the roof again. Sorry about the chimney.',
        'Ember’s here! Don’t worry, I’ve eaten. Well, snacked. Well... I’m starving.',
      ],
      order: [
        'One {recipe}, please! I’ll start with one.',
        'A {recipe}, darling. Extra crispy. I can help with that.',
        'I’d adore a {recipe}! I’ll pay in gold. I have SO much gold.',
      ],
      happy: [
        'Scrumptious! Better than Barnaby’s third verse.',
        'Oh, marvellous! *a small, joyful puff of smoke*',
        'Delightful! Here’s a tip. It’s a gold bar. Too much? It’s too much. Keep it.',
      ],
      grumpy: [
        'I’m trying very hard not to toast anything.',
        '*smoke curls from her nostrils* Sorry. Hungry smoke.',
        'I’m being very patient. For a dragon. Which is not very.',
      ],
      waiting: ['*carefully does not sneeze*', 'Is it hot in here, or is it me? It’s me. Sorry.', '*taps claws politely, leaving small grooves in the counter*'],
      banter: [
        'Barnaby’s writing a sequel about my table manners. They’re excellent, thank you.',
        'Pip’s hatchling calls me Auntie Ember. I’ve never been happier.',
        'Gold is lovely, but have you tried a well-seasoned stew?',
      ],
    },
    story: [
      {
        title: 'The Roof',
        arrive: [
          g('Hello! You must be the Wordsmith! Barnaby talks about you constantly.', 'happy'),
          b('Barnaby talks about everything constantly.'),
          g('I’m Ember. I’m a dragon. I promise I’m here for the food, not the townsfolk.'),
          g('Townsfolk are far too crunchy. So I’m told.'),
        ],
        order: 'One {recipe}, please! A big one! The biggest!',
        done: [g('DELICIOUS! I’ll be back. Many times. Brace yourselves.', 'happy')],
        reward: { coins: 100 },
      },
      {
        title: 'Hiccups',
        arrive: [
          g('*hic* Oh no. *hic* Dragon hiccups.', 'surprised'),
          b('Is that bad?'),
          g('*hic* Only for curtains.'),
        ],
        order: 'A {recipe}, quickly! Food cures hiccups!',
        done: [g('Cured! Only one curtain lost. I’ll pay for it. With a small mountain of gold.', 'happy')],
        reward: { coins: 120 },
      },
      {
        title: 'The Hoard',
        arrive: [
          g('Confession: my hoard has become boring.', 'sad'),
          g('Gold, gold, gold. You can’t eat gold. I’ve tried. It disagrees with me.'),
          b('You could hoard something else?'),
          g('Ooh! Like recipes! A recipe hoard!', 'happy'),
        ],
        order: 'Start my new hoard with a {recipe}!',
        done: [g('One recipe hoarded! A dragon’s life has meaning again.', 'happy')],
        reward: { coins: 150 },
      },
      {
        title: 'Auntie Ember',
        arrive: [
          g('I met Pip’s little hatchling! A baby dragon, sold as a potato! The scandal!', 'happy'),
          g('She sneezed a spark at Squeak’s tail. Tiny flame. He’s fine. Very dramatic about it, though.'),
          b('You’re going to be the cool aunt, aren’t you?'),
          g('The COOLEST aunt. Ironic, since I run at about eight hundred degrees.'),
        ],
        order: 'A {recipe}, to celebrate being an auntie!',
        done: [g('I’ll teach her to fly, to roar, and to use a napkin. The important things.')],
        reward: { coins: 150 },
        after: ['pip'],
      },
      {
        title: 'The Hearth',
        arrive: [
          g('Wordsmith, you’ve been so kind to a big, hungry dragon.', 'happy'),
          g('Allow me to light your hearth properly. A dragon-kindled fire never goes out.'),
          b('Please aim carefully. PLEASE.', 'surprised'),
          g('*FWOOSH* ...There! Only slightly singed the tankard.'),
          b('I’M FINE.', 'grumpy'),
        ],
        order: 'One last thing: a {recipe}, cooked on MY fire!',
        done: [g('A great fire for a great tavern. Now all you need is a thousand guests. It’ll get there.', 'happy')],
        reward: { coins: 200, furniture: 'hearth-dragon' },
      },
    ],
  },
];
