import type { RecipeDef } from '../game/types';

/**
 * Every order is a recipe. Each slot is an ingredient conjured by a word of at least `min` letters;
 * `all` slots are the secret ingredient and need a word that uses every letter.
 */
export const RECIPES: RecipeDef[] = [
  // ── Tier 1 · five letters ──────────────────────────────────────────────
  {
    id: 'frothy-ale',
    name: 'Frothy Ale',
    icon: 'ale',
    tier: 1,
    letters: 5,
    slots: [
      { ingredient: 'hops', min: 3 },
      { ingredient: 'grain', min: 3 },
      { ingredient: 'honey', min: 4 },
    ],
    price: 12,
    patience: 90,
    unlockLevel: 1,
    cost: 0,
    starter: true,
    blurb: 'Brewed by saying "ale" very firmly at a barrel until it gives in.',
  },
  {
    id: 'hearty-stew',
    name: 'Hearty Stew',
    icon: 'stew',
    tier: 1,
    letters: 5,
    slots: [
      { ingredient: 'carrot', min: 3 },
      { ingredient: 'potato', min: 3 },
      { ingredient: 'meat', min: 4 },
    ],
    price: 14,
    patience: 95,
    unlockLevel: 1,
    cost: 0,
    starter: true,
    blurb: 'Contains at least one vegetable. Probably. We stopped checking.',
  },
  {
    id: 'barkroot-tea',
    name: 'Barkroot Tea',
    icon: 'tea',
    tier: 1,
    letters: 5,
    slots: [
      { ingredient: 'herb', min: 3 },
      { ingredient: 'herb', min: 3 },
      { ingredient: 'honey', min: 3 },
      { ingredient: 'milk', min: 3 },
    ],
    price: 15,
    patience: 100,
    unlockLevel: 2,
    cost: 70,
    blurb: 'Steeped for exactly one ent-minute, which is roughly a fortnight.',
  },
  {
    id: 'buttered-bread',
    name: 'Buttered Bread',
    icon: 'bread',
    tier: 1,
    letters: 5,
    slots: [
      { ingredient: 'grain', min: 3 },
      { ingredient: 'herb', min: 3 },
      { ingredient: 'butter', min: 5, all: true },
    ],
    price: 17,
    patience: 100,
    unlockLevel: 2,
    cost: 90,
    blurb: 'The butter is the secret ingredient. It is not a secret. It is on the bread.',
  },

  // ── Tier 2 · six letters ───────────────────────────────────────────────
  {
    id: 'mushroom-pie',
    name: 'Mushroom Pie',
    icon: 'pie',
    tier: 2,
    letters: 6,
    slots: [
      { ingredient: 'mushroom', min: 3 },
      { ingredient: 'butter', min: 4 },
      { ingredient: 'grain', min: 4 },
      { ingredient: 'herb', min: 5 },
    ],
    price: 24,
    patience: 120,
    unlockLevel: 3,
    cost: 180,
    blurb: 'Made with only the friendliest mushrooms. The unfriendly ones made their own pie.',
  },
  {
    id: 'cheese-board',
    name: 'Stinky Cheese Board',
    icon: 'cheese',
    tier: 2,
    letters: 6,
    slots: [
      { ingredient: 'cheese', min: 3 },
      { ingredient: 'apple', min: 3 },
      { ingredient: 'grain', min: 4 },
      { ingredient: 'cheese', min: 5 },
    ],
    price: 24,
    patience: 120,
    unlockLevel: 3,
    cost: 200,
    blurb: 'Aged in a cave. The cave has asked for it back.',
  },
  {
    id: 'honey-mead',
    name: 'Honey Mead',
    icon: 'mead',
    tier: 2,
    letters: 6,
    slots: [
      { ingredient: 'honey', min: 4 },
      { ingredient: 'berry', min: 4 },
      { ingredient: 'magic', min: 6, all: true },
    ],
    price: 27,
    patience: 125,
    unlockLevel: 3,
    cost: 220,
    blurb: 'The bees were paid in compliments. They drive a hard bargain.',
  },
  {
    id: 'fish-chowder',
    name: "Fisherman's Chowder",
    icon: 'chowder',
    tier: 2,
    letters: 6,
    slots: [
      { ingredient: 'fish', min: 3 },
      { ingredient: 'potato', min: 4 },
      { ingredient: 'milk', min: 4 },
      { ingredient: 'onion', min: 5 },
    ],
    price: 26,
    patience: 125,
    unlockLevel: 4,
    cost: 260,
    blurb: 'The fish volunteered. Mostly.',
  },
  {
    id: 'goblin-goulash',
    name: 'Goblin Goulash',
    icon: 'goulash',
    tier: 2,
    letters: 6,
    slots: [
      { ingredient: 'sock', min: 3 },
      { ingredient: 'mushroom', min: 3 },
      { ingredient: 'meat', min: 4 },
      { ingredient: 'onion', min: 4 },
      { ingredient: 'pepper', min: 5 },
    ],
    price: 29,
    patience: 135,
    unlockLevel: 4,
    cost: 280,
    blurb: 'Traditional goblin recipe. The sock is for flavour. Please do not eat the sock.',
  },
  {
    id: 'sea-salt-grog',
    name: 'Sea-Salt Grog',
    icon: 'grog',
    tier: 2,
    letters: 6,
    slots: [
      { ingredient: 'salt', min: 3 },
      { ingredient: 'apple', min: 4 },
      { ingredient: 'hops', min: 4 },
      { ingredient: 'magic', min: 6, all: true },
    ],
    price: 30,
    patience: 130,
    unlockLevel: 5,
    cost: 320,
    blurb: 'Tastes like adventure. Also like the sea. Mostly like the sea.',
  },
  {
    id: 'knightly-kebab',
    name: 'Knightly Kebabs',
    icon: 'kebab',
    tier: 2,
    letters: 6,
    slots: [
      { ingredient: 'meat', min: 3 },
      { ingredient: 'onion', min: 4 },
      { ingredient: 'pepper', min: 4 },
      { ingredient: 'fire', min: 5 },
    ],
    price: 34,
    patience: 130,
    unlockLevel: 1,
    cost: 0,
    special: true,
    blurb: 'Grilled on the Holy Grill. Blessed, skewered, and slightly smoky.',
  },

  // ── Tier 3 · seven letters ─────────────────────────────────────────────
  {
    id: 'roast-boar',
    name: 'Roast Boar',
    icon: 'roast',
    tier: 3,
    letters: 7,
    slots: [
      { ingredient: 'meat', min: 4 },
      { ingredient: 'apple', min: 4 },
      { ingredient: 'herb', min: 5 },
      { ingredient: 'fire', min: 6 },
    ],
    price: 38,
    patience: 150,
    unlockLevel: 5,
    cost: 420,
    blurb: 'The boar was very rude. This is nobody’s fault but the boar’s.',
  },
  {
    id: 'calcium-shake',
    name: 'Calcium Shake',
    icon: 'shake',
    tier: 3,
    letters: 7,
    slots: [
      { ingredient: 'milk', min: 3 },
      { ingredient: 'bone', min: 4 },
      { ingredient: 'berry', min: 5 },
      { ingredient: 'moon', min: 6 },
    ],
    price: 36,
    patience: 150,
    unlockLevel: 5,
    cost: 400,
    blurb: 'Popular with skeletons. It goes straight through them, but they enjoy the gesture.',
  },
  {
    id: 'wizards-fizz',
    name: "Wizard's Fizz",
    icon: 'fizz',
    tier: 3,
    letters: 7,
    slots: [
      { ingredient: 'berry', min: 3 },
      { ingredient: 'honey', min: 4 },
      { ingredient: 'magic', min: 5 },
      { ingredient: 'moon', min: 7, all: true },
    ],
    price: 42,
    patience: 155,
    unlockLevel: 6,
    cost: 480,
    blurb: 'Side effects include glowing, floating, and briefly speaking fluent Duck.',
  },
  {
    id: 'dwarven-stout',
    name: 'Dwarven Stout',
    icon: 'stout',
    tier: 3,
    letters: 7,
    slots: [
      { ingredient: 'hops', min: 4 },
      { ingredient: 'grain', min: 4 },
      { ingredient: 'grain', min: 5 },
      { ingredient: 'fire', min: 7, all: true },
    ],
    price: 44,
    patience: 160,
    unlockLevel: 7,
    cost: 520,
    blurb: 'So thick you can stand a spoon in it. Grizelda stands a hammer in it.',
  },

  // ── Tier 4 · seven and eight letters ───────────────────────────────────
  {
    id: 'dragon-chili',
    name: 'Dragon Pepper Chili',
    icon: 'chili',
    tier: 4,
    letters: 7,
    slots: [
      { ingredient: 'pepper', min: 4 },
      { ingredient: 'meat', min: 5 },
      { ingredient: 'onion', min: 5 },
      { ingredient: 'fire', min: 7, all: true },
    ],
    price: 55,
    patience: 170,
    unlockLevel: 8,
    cost: 800,
    blurb: 'Rated "mild" by dragons. Everyone else has signed a waiver.',
  },
  {
    id: 'moonberry-tart',
    name: 'Moonberry Tart',
    icon: 'tart',
    tier: 4,
    letters: 8,
    slots: [
      { ingredient: 'berry', min: 4 },
      { ingredient: 'butter', min: 4 },
      { ingredient: 'egg', min: 5 },
      { ingredient: 'moon', min: 6 },
      { ingredient: 'magic', min: 8, all: true },
    ],
    price: 62,
    patience: 190,
    unlockLevel: 9,
    cost: 950,
    blurb: 'Moonberries only ripen under a full moon, so this tart is very sleepy.',
  },
  {
    id: 'royal-feast',
    name: 'Royal Feast Pie',
    icon: 'feast',
    tier: 4,
    letters: 8,
    slots: [
      { ingredient: 'meat', min: 4 },
      { ingredient: 'mushroom', min: 5 },
      { ingredient: 'egg', min: 5 },
      { ingredient: 'butter', min: 6 },
      { ingredient: 'crown', min: 8, all: true },
    ],
    price: 75,
    patience: 200,
    unlockLevel: 10,
    cost: 1200,
    blurb: 'Twenty-four blackbirds were considered, then politely declined.',
  },
];
