import type { TownsfolkDef } from '../game/types';

/** Everyday regulars who fill the tavern between story guests. */
export const TOWNSFOLK: TownsfolkDef[] = [
  {
    id: 'farmer',
    title: 'Farmer',
    names: ['Tilly', 'Hob', 'Marigold', 'Bramwell', 'Ned', 'Clover'],
    looks: [
      {
        species: 'human',
        skin: '#e8b48f',
        hair: '#8b5a2b',
        hairStyle: 'short',
        hat: 'strawhat',
        hatColor: '#e2c26b',
        hatAccent: '#b8412f',
        outfitStyle: 'apron',
        outfit: '#6f8f3a',
        outfitAccent: '#c9a36a',
        eyes: 'dot',
        nose: 'button',
        accessories: ['freckles'],
      },
      {
        species: 'halfling',
        skin: '#f0c4a0',
        hair: '#d9a441',
        hairStyle: 'curly',
        hat: 'strawhat',
        hatColor: '#e2c26b',
        hatAccent: '#3f6fb0',
        outfitStyle: 'apron',
        outfit: '#9a6a3a',
        outfitAccent: '#e8d8b0',
        eyes: 'wide',
        nose: 'button',
        accessories: ['blush'],
      },
      {
        species: 'human',
        skin: '#a8694a',
        hair: '#2f1f1a',
        hairStyle: 'bun',
        hat: 'none',
        outfitStyle: 'apron',
        outfit: '#7a8f3a',
        outfitAccent: '#e8d8b0',
        eyes: 'dot',
        nose: 'button',
        accessories: ['freckles'],
      },
    ],
    lines: {
      greet: [
        'Evening! Long day in the fields.',
        'The turnips are revolting again. Not the gross way. The uprising way.',
        'Evening! I’ve left the cows in charge. What could go wrong?',
      ],
      order: [
        'A {recipe}, please! I’ve earned it.',
        'One {recipe}. Nothing with turnips.',
        'A {recipe}, if you’d be so kind.',
      ],
      happy: [
        'Lovely! Better than turnips. Everything’s better than turnips.',
        'Now that’s proper food!',
        'Tastes like a good harvest!',
      ],
      grumpy: ['The cows will be wondering where I am.', 'I could’ve grown this myself by now.'],
      waiting: ['*yawns*', '*picks a bit of hay out of their hair*'],
    },
  },
  {
    id: 'guard',
    title: 'Town Guard',
    names: ['Brom', 'Hilda', 'Garrick', 'Una', 'Tobias'],
    looks: [
      {
        species: 'human',
        skin: '#f0c8a8',
        hair: '#5a3a22',
        hairStyle: 'short',
        beard: 'stubble',
        hat: 'helmet',
        hatColor: '#9aa3ad',
        hatAccent: '#b33a3a',
        outfitStyle: 'armor',
        outfit: '#b33a3a',
        outfitAccent: '#9aa3ad',
        eyes: 'dot',
        nose: 'big',
      },
      {
        species: 'orc',
        skin: '#7d9a6a',
        hair: '#2a2a2a',
        hairStyle: 'short',
        hat: 'helmet',
        hatColor: '#8e969e',
        hatAccent: '#b33a3a',
        outfitStyle: 'armor',
        outfit: '#b33a3a',
        outfitAccent: '#8e969e',
        eyes: 'dot',
        nose: 'big',
        accessories: ['tusks'],
      },
      {
        species: 'dwarf',
        skin: '#e2a67e',
        hair: '#3b2a1e',
        hairStyle: 'short',
        beard: 'short',
        hat: 'helmet',
        hatColor: '#9aa3ad',
        hatAccent: '#b33a3a',
        outfitStyle: 'armor',
        outfit: '#b33a3a',
        outfitAccent: '#9aa3ad',
        eyes: 'dot',
        nose: 'big',
      },
    ],
    lines: {
      greet: [
        'Halt! Who goes... oh, it’s the tavern. Evening.',
        'On my break. Don’t tell the sergeant.',
        'All quiet in town. Too quiet. Suspiciously... no, it’s just quiet.',
      ],
      order: [
        'A {recipe}, citizen. For the good of the realm.',
        'One {recipe}. Quickly, before my break ends.',
        'A {recipe}. I’ve been guarding a door all day.',
      ],
      happy: [
        'The realm is safe, and so is my dinner.',
        'Excellent. I shall guard this memory forever.',
        'Ten out of ten. No arrests necessary.',
      ],
      grumpy: [
        'Loitering is technically a crime, you know. Mine, currently.',
        'My break is nearly over...',
      ],
      waiting: ['*stands to attention while waiting*', '*eyes the talking tankard suspiciously*'],
    },
  },
  {
    id: 'merchant',
    title: 'Travelling Merchant',
    names: ['Olwin', 'Fennick', 'Saffra', 'Dobbs'],
    looks: [
      {
        species: 'gnome',
        skin: '#f2bfa0',
        hair: '#b0b0b0',
        hairStyle: 'short',
        beard: 'goatee',
        hat: 'cap',
        hatColor: '#3f6fb0',
        hatAccent: '#e3b448',
        outfitStyle: 'coat',
        outfit: '#3f6fb0',
        outfitAccent: '#e3b448',
        eyes: 'dot',
        nose: 'big',
        accessories: ['glasses'],
      },
      {
        species: 'human',
        skin: '#c68a62',
        hair: '#1f1f1f',
        hairStyle: 'long',
        hat: 'scarf',
        hatColor: '#c0582b',
        hatAccent: '#f2c14e',
        outfitStyle: 'coat',
        outfit: '#8a3b5a',
        outfitAccent: '#f2c14e',
        eyes: 'dot',
        nose: 'button',
        accessories: ['earring'],
      },
    ],
    lines: {
      greet: [
        'Just passing through! Selling spoons. Want a spoon?',
        'What a charming tavern! I sell charms, you know.',
        'Evening! Business is good. Well, business is.',
      ],
      order: [
        'A {recipe}, please. I’ll trade you a spoon for it. No? Coins, then.',
        'One {recipe}! Travelling makes a merchant hungry.',
        'A {recipe}. Best price in town, I assume?',
      ],
      happy: [
        'Worth every coin. And I count coins very carefully.',
        'I’ll tell everyone on my route about this place!',
        'Delicious. I’d stock this if it wouldn’t go cold.',
      ],
      grumpy: [
        'Time is money, and I’m spending both.',
        'I’ve a caravan leaving at dawn, you know.',
      ],
      waiting: ['*polishes a spoon hopefully*', '*counts coins twice*'],
    },
  },
  {
    id: 'apprentice',
    title: 'Wizard’s Apprentice',
    names: ['Wren', 'Pim', 'Juniper', 'Alder', 'Sprocket'],
    looks: [
      {
        species: 'elf',
        skin: '#f4d2b8',
        hair: '#e8d27a',
        hairStyle: 'long',
        hat: 'wizard',
        hatColor: '#2f7d7a',
        hatAccent: '#e8e8e8',
        outfitStyle: 'robe',
        outfit: '#2f7d7a',
        outfitAccent: '#e8e8e8',
        eyes: 'wide',
        nose: 'button',
      },
      {
        species: 'human',
        skin: '#9c6644',
        hair: '#8b4fb3',
        hairStyle: 'spiky',
        hat: 'none',
        outfitStyle: 'robe',
        outfit: '#5b3b8c',
        outfitAccent: '#8ee0d0',
        eyes: 'wide',
        nose: 'button',
        accessories: ['glasses'],
      },
    ],
    lines: {
      greet: [
        'My master turned my eyebrows purple again.',
        'I’ve been practising levitation all day. I’m exhausted. Also, slightly floating.',
        'Is this where Fizzlewick drinks? I need to hide from him.',
      ],
      order: [
        'A {recipe}, please. Magic is hungry work.',
        'One {recipe}! Before my master finds me.',
        'A {recipe}. No enchantments, please.',
      ],
      happy: [
        'That’s better magic than anything I can do!',
        'Delicious! My eyebrows feel less purple already.',
        'Wow! Can you teach me that spell?',
      ],
      grumpy: [
        'I could summon it faster. Well. I could summon something.',
        'My homework is due tomorrow...',
      ],
      waiting: ['*accidentally makes the napkin float*', '*reads a spellbook upside down*'],
    },
  },
  {
    id: 'mercenary',
    title: 'Orc Mercenary',
    names: ['Grok', 'Urza', 'Thrag', 'Morg'],
    looks: [
      {
        species: 'orc',
        skin: '#6f8f55',
        hair: '#1f1f1f',
        hairStyle: 'wild',
        hat: 'none',
        outfitStyle: 'tunic',
        outfit: '#5a4030',
        outfitAccent: '#9aa3ad',
        eyes: 'dot',
        nose: 'big',
        accessories: ['tusks', 'scar'],
      },
      {
        species: 'orc',
        skin: '#8a9a6a',
        hair: '#3a2a2a',
        hairStyle: 'braids',
        hat: 'none',
        outfitStyle: 'tunic',
        outfit: '#6b3030',
        outfitAccent: '#c0a060',
        eyes: 'dot',
        nose: 'big',
        accessories: ['tusks', 'earring'],
      },
    ],
    lines: {
      greet: [
        'Grok hungry. Grok also has book club on Thursdays.',
        'Mercenary work slow. Everyone too nice lately. Grok blames this tavern.',
        'Evening. Grok wiped boots. Grok is civilised.',
      ],
      order: [
        '{recipe}. Big. Please. Grok learned please.',
        'One {recipe}. Grok will fight anyone who says it is not delicious.',
        'Grok wants {recipe}.',
      ],
      happy: [
        'GOOD. Grok happy. Grok hug? No. Grok nod.',
        'Tasty! Grok will write review. Grok is learning letters.',
        'Best food. Better than battle.',
      ],
      grumpy: [
        'Grok is patient. Grok is patient. Grok is patient.',
        'Grok’s stomach is making war noises.',
      ],
      waiting: ['*cracks knuckles, then politely folds hands*', '*reads a very small poetry book*'],
    },
  },
  {
    id: 'ranger',
    title: 'Elf Ranger',
    names: ['Sylwen', 'Faelar', 'Ithil', 'Nimue'],
    looks: [
      {
        species: 'elf',
        skin: '#f1d3bd',
        hair: '#f0e0b0',
        hairStyle: 'long',
        hat: 'hood',
        hatColor: '#3f6b3a',
        hatAccent: '#8fbf6a',
        outfitStyle: 'tunic',
        outfit: '#3f6b3a',
        outfitAccent: '#8a6a44',
        eyes: 'dot',
        nose: 'pointy',
      },
      {
        species: 'elf',
        skin: '#b07a55',
        hair: '#2a1a12',
        hairStyle: 'braids',
        hat: 'none',
        outfitStyle: 'tunic',
        outfit: '#4d6b3a',
        outfitAccent: '#c0a060',
        eyes: 'dot',
        nose: 'pointy',
        accessories: ['earring'],
      },
    ],
    lines: {
      greet: [
        'I tracked this smell for three miles. It led here.',
        'I’ve been in the woods for a month. What year is it?',
        'Evening. I’ll sit where I can see the door. Ranger habit.',
      ],
      order: [
        'A {recipe}, please. Something that isn’t berries.',
        'One {recipe}. Woodland rations get dull.',
        'A {recipe}. I hear it’s legendary.',
      ],
      happy: [
        'Exquisite. The forest could learn from you.',
        'Worth the three-mile walk. Every step.',
        'Better than the elven feasts. Don’t tell the elves.',
      ],
      grumpy: [
        'I once waited three days for a deer. This is worse.',
        'Even the owls are asleep now.',
      ],
      waiting: [
        '*sharpens an arrow very quietly*',
        '*listens to the fire as if it’s telling secrets*',
      ],
    },
  },
  {
    id: 'squire',
    title: 'Nervous Squire',
    names: ['Tim', 'Percy', 'Edwin', 'Bess'],
    looks: [
      {
        species: 'human',
        skin: '#f5d0b5',
        hair: '#c47a3a',
        hairStyle: 'short',
        hat: 'none',
        outfitStyle: 'tunic',
        outfit: '#2f5fa7',
        outfitAccent: '#e3b448',
        eyes: 'wide',
        nose: 'button',
        accessories: ['freckles', 'blush'],
      },
    ],
    lines: {
      greet: [
        'M-my knight said to wait here. For six hours.',
        'Is this the tavern with the talking cup? Please don’t let it talk to me.',
        'I’m on a quest! To fetch my knight’s laundry.',
      ],
      order: [
        'A {recipe}, please. If that’s alright. Is it alright?',
        'One {recipe}. Sorry. Please. Thank you. Sorry.',
        'Could I get a {recipe}? Sorry to bother you.',
      ],
      happy: [
        'Oh wow, thank you! Sorry! Thank you!',
        'That was brave. Of you. Cooking. Very brave.',
        'I feel ready for anything now! Well, for most things.',
      ],
      grumpy: ['Sorry, not to rush, but... sorry.', 'My knight will be wondering... sorry.'],
      waiting: ['*fidgets with a wooden sword*', 'Sorry. Just... sorry.'],
    },
  },
  {
    id: 'monk',
    title: 'Wandering Monk',
    names: ['Brother Anselm', 'Sister Maude', 'Brother Tuck'],
    looks: [
      {
        species: 'human',
        skin: '#d9a07a',
        hairStyle: 'none',
        hat: 'none',
        outfitStyle: 'robe',
        outfit: '#8a5a36',
        outfitAccent: '#c9a36a',
        eyes: 'sleepy',
        nose: 'button',
        accessories: ['blush'],
      },
      {
        species: 'halfling',
        skin: '#f0c4a0',
        hair: '#e0e0e0',
        hairStyle: 'short',
        hat: 'hood',
        hatColor: '#8a5a36',
        hatAccent: '#c9a36a',
        outfitStyle: 'robe',
        outfit: '#8a5a36',
        outfitAccent: '#c9a36a',
        eyes: 'sleepy',
        nose: 'button',
      },
    ],
    lines: {
      greet: [
        'I have taken a vow of silence. ...Oops.',
        'Peace be with you. And with your kitchen.',
        'I have walked a thousand miles in search of inner peace. And snacks.',
      ],
      order: [
        'A {recipe}, please. Humbly.',
        'One {recipe}. It is written. Well, I just wrote it.',
        'May I have a {recipe}? The path to wisdom is paved with dinner.',
      ],
      happy: [
        'Enlightening. Truly.',
        'I have found inner peace. It tastes of gravy.',
        'Blessings upon this kitchen.',
      ],
      grumpy: [
        'Patience is a virtue. I am running low on virtue.',
        'I am meditating. Very. Hungrily.',
      ],
      waiting: ['*hums a low, peaceful note*', '*balances a spoon on one finger*'],
    },
  },
  {
    id: 'miner',
    title: 'Dwarf Miner',
    names: ['Durin', 'Brunhild', 'Thorgar', 'Kili'],
    looks: [
      {
        species: 'dwarf',
        skin: '#e0a57a',
        hair: '#5a3a22',
        hairStyle: 'short',
        beard: 'long',
        hat: 'helmet',
        hatColor: '#d9a441',
        outfitStyle: 'apron',
        outfit: '#5a5048',
        outfitAccent: '#c47a2c',
        eyes: 'dot',
        nose: 'big',
      },
      {
        species: 'dwarf',
        skin: '#c68a62',
        hair: '#1f1f1f',
        hairStyle: 'braids',
        beard: 'braided',
        hat: 'none',
        outfitStyle: 'apron',
        outfit: '#4d4a60',
        outfitAccent: '#c47a2c',
        eyes: 'dot',
        nose: 'big',
      },
    ],
    lines: {
      greet: [
        'Dug a tunnel straight here. Sorry about your cellar.',
        'Evening! Found a gem today. Traded it for dinner money.',
        'Ah, surface air. Overrated. Surface food, though!',
      ],
      order: [
        'A {recipe}! Dwarf portion.',
        'One {recipe}. Mining makes you hungry. So does breathing.',
        'A {recipe}, if ye please.',
      ],
      happy: [
        'Better than any gem I’ve dug up!',
        'Hearty! Proper dwarf food, that.',
        'Rock solid. That’s a compliment.',
      ],
      grumpy: [
        'I could have dug to the other side of the world by now.',
        'Hmph. Slower than a stalagmite.',
      ],
      waiting: ['*taps the counter with a pickaxe*', '*shakes dust out of their beard*'],
    },
  },
  {
    id: 'granny',
    title: 'Halfling Granny',
    names: ['Granny Bumble', 'Nana Pickett', 'Old Mother Tansy'],
    looks: [
      {
        species: 'halfling',
        skin: '#f2c7a5',
        hair: '#f0f0f0',
        hairStyle: 'bun',
        hat: 'none',
        outfitStyle: 'shawl',
        outfit: '#b34a6a',
        outfitAccent: '#f0e0c0',
        eyes: 'dot',
        nose: 'button',
        accessories: ['glasses', 'wrinkles', 'blush'],
      },
    ],
    lines: {
      greet: [
        'Back in my day, words were free and food was expensive. Or the other way round.',
        'Hello, dearie! You look thin. Are you eating?',
        'I’ve brought my knitting. Don’t mind me.',
      ],
      order: [
        'A {recipe}, dearie. And don’t forget the vegetables.',
        'One {recipe}, please. Not too spicy, my heart can’t take it.',
        'A {recipe} for an old lady, if you please.',
      ],
      happy: [
        'Almost as good as mine! Almost.',
        'You’re a treasure, dearie. A treasure.',
        'Lovely. I’ll knit you a scarf.',
      ],
      grumpy: [
        'I’ve knitted half a sock waiting, dearie.',
        'In my day, service was faster. And the walk here was uphill.',
      ],
      waiting: ['*click click click* goes the knitting', 'Have you met my grandson? He’s single.'],
    },
  },
  {
    id: 'tourist',
    title: 'Gnome Tourist',
    names: ['Nibsy', 'Fizzbin', 'Tock', 'Posy'],
    looks: [
      {
        species: 'gnome',
        skin: '#f5c6aa',
        hair: '#e07a3a',
        hairStyle: 'wild',
        hat: 'strawhat',
        hatColor: '#f2d27a',
        hatAccent: '#e05a8a',
        outfitStyle: 'vest',
        outfit: '#e05a8a',
        outfitAccent: '#fff3c0',
        eyes: 'wide',
        nose: 'big',
        accessories: ['glasses'],
      },
    ],
    lines: {
      greet: [
        'Is this THE Wordsmith Tavern? I came all the way from the next village!',
        'Ooh! Is that the famous talking tankard? Can I touch it?',
        'I’m on holiday! My first one in ninety years!',
      ],
      order: [
        'I’ll have whatever the locals have! A {recipe}!',
        'One {recipe}, please! I read about it in a guidebook.',
        'A {recipe}! Is it true it’s made from words?',
      ],
      happy: [
        'Wait till I tell everyone back home!',
        'Five stars! Would travel two villages for this!',
        'I’m getting this recipe tattooed. Small tattoo. Very small.',
      ],
      grumpy: ['My tour group leaves in ten minutes!', 'The guidebook said service was quick...'],
      waiting: ['*sketches Barley in a little notebook*', '*takes a mental picture*'],
    },
  },
];
